on:
    workflow_dispatch:
        
        

jobs:
    QA-SSEC:
      runs-on: ubuntu-latest
      environment: QA
      steps:
        - name: Print Secret Value from QA environment
          run: echo "message --> ${{ secrets.QA_SECRETS }}"


    PRD-SSEC:
      runs-on: ubuntu-latest
      environment: PRD
      steps:
        - name: Print Secret Value from PRD environment
          run: echo "message --> ${{ secrets.PRD_SECRETS }}"
          
          
    REPO-SSEC:
      runs-on: ubuntu-latest
      steps:
        - name: Print Secret Value from  Repo_secrets
          run: echo "message --> ${{ secrets.REPO_SECRETS }}"
