on:
    workflow_dispatch:
        
        

jobs:
    QA-SSEC:
      runs-on: ubuntu-latest
      environment: QA
      steps:
        - name: Print Secret and Variable from QA environment
          run:  |
                 echo "message --> ${{ secrets.QA_SECRETS }}"
                  echo "message --> ${{ vars.VAR_QA }}"

    PRD-SSEC:
      runs-on: ubuntu-latest
      environment: PRD
      steps:
        - name: Print Secret and Variable from PRD environment
          run: |
                echo "message --> ${{ secrets.PRD_SECRETS }}"
                echo "message --> ${{ vars.VAR_PRD }}"
          
          
    REPO-SSEC:
      runs-on: ubuntu-latest
      steps:
        - name: Print Secret and Variable Repo_secrets
          run: |
               echo "message --> ${{ secrets.REPO_SECRETS }}"
                echo "message --> ${{ vars.VAR_REPO }}"

 
    Azure-Login:
      runs-on: ubuntu-latest
      steps:

        - name: Azure login With SP
          uses: azure/login@v2
          with:  
             creds: ${{ secrets.AZURE_CREDENTIALS }}      
      
#        - name: Azure login
#          uses: azure/login@v3
#          with:
#            client-id: ${{ secrets.CLIENT_ID }}
#           tenant-id: ${{ secrets.TEN_ID }}
#            subscription-id: ${{ secrets.SUB_ID }}

        - name: Azure CLI script
          uses: azure/cli@v2
          with:
            azcliversion: latest
            inlineScript: |
                az account show                